# Generated by Django 5.2.4 on 2025-07-26 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[a-zA-Z0-9\\s@.+\\-_]+$')]),
        ),
    ]
