# Generated by Django 5.2.4 on 2025-07-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('badge_type', models.CharField(choices=[('pitch-master', 'Pitch Master'), ('ideation-expert', 'Ideation Expert'), ('validation-pro', 'Validation Pro'), ('mvp-builder', 'MVP Builder'), ('launch-champion', 'Launch Champion'), ('feedback-guru', 'Feedback Guru'), ('monetization-master', 'Monetization Master')], max_length=50)),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_description', models.TextField()),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('minted', 'Minted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('phase_completed', models.CharField(max_length=50)),
                ('minted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-minted_at'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
